### ISSUE TITLE
Evaluate Consul

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#109]
http://consul.io

How does Consul compare to Shoal? Is it a viable/attractive alternative?

Consul itself is federation-like, in the sense that you can have a cluster of redundant Consul servers (which elect a leader amongst themselves) and a client can query any Consul agent OR server to discover any service. It includes the concept of health checking and seems generic and multi-purpose.

It's free, open-source, has a very active community and started around Dec. 2013.
This describes how Consul compares to other service discovery systems:
https://www.consul.io/intro/vs/custom.html

**Comment by colsond** [comment]
I looked into consul a fair amount when considering it for the cloud scheduler redesign. Consul certainly would be capable of replicating the functionality of shoal but the issue is that you would basically need to recreate to shoal functionality with consul.

Consul provides a core structure but the user must define all health checks, verification, and service types through configuration and scripts. Consul is also a pretty heavyweight tool and it would probably be overkill to replace the shoal service. 

If we were to bring in a consul cluster to support an array of heprc services we could consider brining the shoal functionality to consul but alone it certainly would not be worth it.
