### ISSUE TITLE
shoal_server.config could first look at env variable for config file path

### ISSUE THREAD

**Issue by AndreCharbonneau** [hep-gc/shoal#71]
For extra flexibility, the shoal_server configuration could first look at an environment variable (i.e., SHOAL_SERVER_CONFIG) for a config file path and load it from that path if given.

**Comment by colsond** [comment]
After a lot of digging there are a few problems with this.
Shoal server is actually run through apache (more specifically its run as the apache user). The apache user has no shell available so using a global env variable won't work.

Apache has a way of importing "enviroment" variables (`SetEnv MY_VARIABLE_NAME my_variable value`) in the apache conf file so they can be used by whatever web framework might be running on top of apache. In our case (web.py/wsgi) said variables can be accessed by `web.ctx.env['MY_VARIABLE_NAME']` which seems great.

The problem is that web.py doesn't load the context until the first request of the web server has been made. This pretty much makes the environment variable useless for configuration since the webserver has to be active before the variables can be accessed this way.

**Comment by rptaylor** [comment]
I think this was brought up back when we envisioned Shoal agent as being easy to install and run from e.g. a user's home directory instead of installing into standard system locations. Doesn't seem as important anymore.
